---
name: End-to-end tests

on:
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  schedule:
    - cron: "0 18 * * 5"  # Run every Friday at 18:00 UTC

concurrency: end_to_end_testing_environment

jobs:
  Test:
    environment: end_to_end_testing_environment
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        capabilities:
          # Desktop browsers
          - platform: "WIN10"
            browserName: "chrome"
            version: "48"
          - platform: "WIN10"
            browserName: "chrome"
            version: "latest"
          - platform: "WIN10"
            browserName: "firefox"
            version: "44"
          - platform: "WIN10"
            browserName: "firefox"
            version: "latest"
          - platform: "WIN10"
            browserName: "ie"
            version: "11"
          - platform: "WIN10"
            browserName: "edge"
            version: "latest"
          - platform: "WIN10"
            browserName: "opera"
            version: "50"
          - platform: "WIN10"
            browserName: "opera"
            version: "latest"
          - platform: "SIERRA"
            browserName: "safari"
            version: "11"
          - platform: "BIGSUR"
            browserName: "safari"
            version: "latest"

          # Mobile browsers
          - platformName: "iOS"
            deviceName: "iPhone 6s Plus"
            browserName: "safari"
            version: "10.3"
          - platformName: "iOS"
            deviceName: "iPhone 12 Pro"
            browserName: "safari"
            version: "14.2"
          - platformName: "Android"
            deviceName: "Pixel 2"
            browserName: "chrome"
            version: "7.1"
          - platformName: "Android"
            deviceName: "Galaxy S21"
            browserName: "chrome"
            version: "11.0"

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install `tox`
        run: python3 -m pip install tox

      - name: Generate unique TestingBot Tunnel ID
        run: >
          echo "TUNNEL_ID=TB-$(cat /proc/sys/kernel/random/uuid)" >> $GITHUB_ENV

      - name: Set up TestingBot Tunnel
        uses: testingbot/testingbot-tunnel-action@v1.1.0
        with:
          key: "${{ secrets.TESTINGBOT_KEY }}"
          secret: "${{ secrets.TESTINGBOT_SECRET }}"
          tunnelIdentifier: "${{ env.TUNNEL_ID }}"

      - name: Dump target capabilities to JSON file
        run: >
          echo '{"capabilities": ${{ toJSON(matrix.capabilities) }}}' >>
          ${{ runner.temp }}/capabilities.json

      - name: Run end-to-end tests
        run: >
          python3 -m tox -e py3-end2end --
          --driver TestingBot
          --capability tunnel-identifier "${{ env.TUNNEL_ID }}"
          --capability selenium-host "http://localhost"
          --capability selenium-port "4445"
          --capability build "End-to-end tests #${{ github.run_number }}"
          --capability public "true"
          --variables "${{ runner.temp }}/capabilities.json"
        env:
          TESTINGBOT_KEY: "${{ secrets.TESTINGBOT_KEY }}"
          TESTINGBOT_SECRET: "${{ secrets.TESTINGBOT_SECRET }}"
