---
name: End-to-end tests

on:
  pull_request:
  push:
  schedule:
    - cron: '0 18 * * 5'  # Run every Friday at 18:00 UTC

jobs:
  Test:
    environment: end_to_end_testing_environment
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        target:
          # Desktop browsers
          - os: 'Windows'
            os_version: '10'
            browser: 'Chrome'
            browser_version: '48'
            platform: 'desktop'
          - os: 'Windows'
            os_version: '10'
            browser: 'Chrome'
            browser_version: 'latest'
            platform: 'desktop'
          - os: 'Windows'
            os_version: '10'
            browser: 'Firefox'
            browser_version: '44'
            platform: 'desktop'
          - os: 'Windows'
            os_version: '10'
            browser: 'Firefox'
            browser_version: 'latest'
            platform: 'desktop'
          - os: 'Windows'
            os_version: '10'
            browser: 'IE'
            browser_version: '11'
            platform: 'desktop'
          - os: 'Windows'
            os_version: '10'
            browser: 'Edge'
            browser_version: 'latest'
            platform: 'desktop'
          - os: 'OS X'
            os_version: 'Sierra'
            browser: 'Safari'
            browser_version: '10'
            platform: 'desktop'
          - os: 'OS X'
            os_version: 'Big Sur'
            browser: 'Safari'
            browser_version: 'latest'
            platform: 'desktop'

          # Mobile browsers
          - device: 'iPhone 7 Plus'
            os_version: '10'
            platform: 'mobile'
          - device: 'iPhone 12 Pro'
            os_version: '14'
            platform: 'mobile'
          - device: 'Samsung Galaxy S6'
            os_version: '5.0'
            platform: 'mobile'
          - device: 'Samsung Galaxy S20'
            os_version: '10.0'
            platform: 'mobile'
    env:
      BROWSERSTACK_JOB_ACCESS: "public_url"
    steps:
      # Set up BrowserStack environment and start BrowserStackLocal
      - name: Set up BrowserStack Environment
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project-name: 'REPO_NAME'
          build-name: 'End-to-end test #${{ github.run_number }}'
      - name: Start BrowserStackLocal
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      # End-to-end tests
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install `tox`
        run: python3 -m pip install tox

      - name: Run end-to-end tests (desktop)
        run: >
            python3 -m tox -e py3-end2end --
            --liveserver "bs-local.com:8080"
            --driver BrowserStack
            --capability browserstack.local true
            --capability browserstack.localIdentifier "${{ env.BROWSERSTACK_LOCAL_IDENTIFIER }}"
            --capability project "${{ env.BROWSERSTACK_PROJECT_NAME }}"
            --capability build "${{ env.BROWSERSTACK_BUILD_NAME }}"
            --capability os "${{ matrix.target.os }}"
            --capability os_version "${{ matrix.target.os_version }}"
            --capability browser "${{ matrix.target.browser }}"
            --capability browser_version "${{ matrix.target.browser_version }}"
        if: ${{ matrix.target.platform == 'desktop' }}

      - name: Run end-to-end tests (mobile)
        run: >
            python3 -m tox -e py3-end2end --
            --liveserver "bs-local.com:8080"
            --driver BrowserStack
            --capability browserstack.local true
            --capability browserstack.localIdentifier "${{ env.BROWSERSTACK_LOCAL_IDENTIFIER }}"
            --capability project "${{ env.BROWSERSTACK_PROJECT_NAME }}"
            --capability build "${{ env.BROWSERSTACK_BUILD_NAME }}"
            --capability device "${{ matrix.target.device }}"
            --capability realMobile "true"
            --capability os_version "${{ matrix.target.os_version }}"
        if: ${{ matrix.target.platform == 'mobile' }}

      # Stop BrowserStackLocal
      - name: Stop BrowserStackLocal
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
